import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "./modules/menu/page";
import StatusBar from "./modules/status-bar/page";
import BackgroundImage from "./modules/background-image/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BackgroundImage />
        <div className="flex flex-col justify-center items-center mt-60">
          <div className="xl:w-[80%] w-[90%] m-10">
            <Menu />
            <StatusBar />
            {children}
          </div>
          <p className="text-slate-50 text-xs mb-10">@KarimAAC</p>
        </div>
      </body>
    </html>
  );
}
